### PR TITLE
Fix endless loop when iterating segments

### PR DESCRIPTION
**Pull request by ostefano**
Fix endless loop when running telfhash against https://www.virustotal.com/gui/file/e676b0ef7fda492b2cd057a025893b4674bcd9dce786ef4c4392d5d56433b7e6/detection

### CODE REVIEW

**Comment by ostefano** [comment]
@merces any change you can merge this?

**Comment by merces** [comment]
Sure thing. Thanks for following up on this! And thanks for your PR too. :)

**Comment by ostefano** [comment]
Awesome thx! :)

**Comment by ostefano** [comment]
@merces maybe I should have bumped the version number as well ^_^
Shall I create a new PR or can you commit a quick one-liner?

**Comment by merces** [comment]
@ostefano just did it. 🙂

**Pull request merged**
